---
- name: Define container_enabled
  set_fact:
    container_enabled: "{{ lookup('env', 'ANSIBLE_CONTAINER') | default(0) }}"
    
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: config.yml
- include: ssl.yml
# - include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service: "name=logstash state=started enabled={{ logstash_enabled_on_boot }}"
